v2 final
volkamerlab/kinodata-3D-affinity-prediction pull request #4
Opened 2024-03-28 16:50 UTC by joschka-gross

Changes made during the re-run of all experiments based on kinodata-3d 2.0.0

2024-03-28 18:14 UTC, mbackenkoehler requested changes
See below

2024-03-28 18:14 UTC, mbackenkoehler commented on kinodata/model/complex_transformer.py
> +
This does probably not belong ;)

2024-03-28 18:14 UTC, mbackenkoehler commented on scripts/generate_dataset.py
Maybe add dataset for all rmsd?

2024-03-28 18:14 UTC, mbackenkoehler commented on scripts/generate_splits.py
> +    for rmsd_cutoff in (2.0, 4.0, 6.0):
Also add 100?

2024-03-29 14:29 UTC, joschka-gross commented on scripts/generate_splits.py
> +    for rmsd_cutoff in (2.0, 4.0, 6.0):
Done

2024-03-29 14:29 UTC, joschka-gross commented on kinodata/model/complex_transformer.py
> +
Yes, removed.

2024-03-29 18:44 UTC, mbackenkoehler approved these changes

2024-03-30 10:00 UTC, merged